SET SERVEROUTPUT ON
DECLARE 
    X NUMBER;
BEGIN 
    X:= 10;
    DBMS_OUTPUT.PUT_LINE('ESTE ES EL VALOR DE X EN EL BLOQUE PRINCIPAL := '|| X);

    -- BLOQUE ANIDADO DENTRO DEL BLOQUE PRINCIPAL
    DECLARE 
        Z NUMBER;
    BEGIN
        Z:= 10;
        DBMS_OUTPUT.PUT_LINE('ESTE ES EL VALOR DE X+Z EN EL BLOQUE HIJO := '|| (Z + X) );
    END;
END;