SET SERVEROUTPUT ON

-- TODO: INICIO DEL BLOQUE ANONIMO DE PL/SQL
BEGIN 

-- Mostrar tu Nombre complato por pantalla
DBMS_OUTPUT.PUT_LINE('NOMBRE COMPLETO : ' || 'JUAN CARLOS AVILA MEZA');

-- TODO: FIN DEL BLOQUE ANONIMO DE PL/SQL  
END;